### PR TITLE
Mac port

### PR DESCRIPTION
**Pull request by jpauwels**
These change made it possible for me to build CNTK on OS X 10.11.3. Just a single commit deals with Mac-specific changes, the others correct non-standard linking behaviour that depends on luck and compiler implementation details (I'm surprised CNTK even links on Windows and Linux).

I based this PR on f628e52de2ea1fe91a0a87de107bdcf384679ef0 because the Linux build is currently broken in master. I'll rebase this PR as soon as this is fixed.

I could only test the CPU-only version because I don't have an Nvidia GPU. On the other hand, I set up CI to test the changes with GCC 4.9 and 5.3 both on Linux and Mac, so I'm pretty confident they don't break anything (see [Travis CI](https://travis-ci.org/jpauwels/CNTK/builds/107701923)). Now I'd like someone to verify on a Windows machine.

In order to build on a Mac, you need an `mpic++` that is built with GCC, which doesn't come standard with OS X. If you have homebrew, you can do: `brew install gcc --without-multilib` and then `brew install --cc=gcc openmpi`. You also need Intel MKL, because ACML is not available for Mac, but the former is [freely available](https://software.intel.com/sites/campaigns/nest/) too (since recently).

### CODE REVIEW

**Comment by jpauwels** [comment]
I already tested the changes on Windows myself (see [AppVeyor CI](https://ci.appveyor.com/project/jpauwels/cntk/build/0.1.34)) and after a minor change, everything now compiles under Windows, OS X and Linux (still CPU-only though and based on f628e52).

**Comment by polidore** [comment]
is this going to be merged?  i'd like to use CNTK on my mac!

**Comment by rashoodkhan** [comment]
Any update on this issue?

**Comment by n17s** [comment]
As long as we don't have infrastructure to automatically run nightly tests on OSX, this is extremely hard to do.

**Comment by jpauwels** [comment]
Thanks for finally acknowledging the existence of this pull request, it's only nine months old. If CI testing is the only problem, I made a Travis configuration file too as you can see in my first message. At the time I wrote it, Linux compilation was in a perpetual broken state as well, so your nightly tests weren't working anyway. This PR is probably too old now to be salvaged and I have sort of moved on to competing deep learning toolkits. I might be persuaded to try another mac port starting from the current head if there's enough interest and a chance it might be merged.

**Comment by n17s** [comment]
We use Jenkins, not Travis, on our own infrastructure. In the near future we will move Jenkins to Azure. At that point it will be a matter of Azure having OSX VMs. So it will probably take a long time.

**Comment by jpauwels** [comment]
Travis is free for open-source projects. So why not use it in addition to your own Jenkins? I can provide you with the configuration file.

**Comment by chrisbasoglu** [comment]
Free Travis for OSX related build and test sounds interesting.  Incorporating that into our current Jenkins based flow is not something we have discussed or planed up till now.  We'd need to figure out GPU support, etc...  We look into viability in our next sprint.  Some OSX users have been doing CNTK inside Docker containers (no GPU).

**Comment by Boggartfly** [comment]
@n17s
> We use Jenkins, not Travis, on our own infrastructure. In the near future we will move Jenkins to Azure. At that point it will be a matter of Azure having OSX VMs. So it will probably take a long time.
Apple allows VMs of it's OSX on Apple Hardware Only. Unless MS gets Mac Hardware to run OSX for Azure, there's probably no other way to expect a VM anytime soon.

**Comment by yaronyg** [comment]
@jpauwels For whatever it's worth I'm personally trying to get CNTK CPU only running on macOS again. Right now I'm not worrying about OpenCV or Python support but I plan on getting to them. I just finished getting the key dependencies built on macOS (e.g. C++ 4.8.4, Intel's MKL, OpenMPI, Zlib, LibZip, Protobuf and Boost) and am now going to use your changes as a guide to changing the latest version of CNTK and seeing if I can get things building.

**Comment by cha-zhang** [comment]
We are very interested in having Mac support for CNTK now that CNTK 2.0 has been released. Travis build would be fine for us. If anyone is willing to help, please!

**Comment by cha-zhang** [comment]
This pull request has been too old to merge with the master. Closing it now. 

As I mentioned, we are still interested in MAC support, and if someone could work on it, we will make sure to handle the PR as soon as possible.

**Pull request closed without merging**
