### PR TITLE
Adding transfer learning notebook

### PR DESCRIPTION
**Pull request by noodlefrenzy**
Work known to @chrisbasoglu, adapting existing TL example into a Notebook - he (et.al.) has mentioned that I might need to jump some hoops w.r.t. building and testing.

### CODE REVIEW

**Comment by sayanpa** [comment]
>     "* Transfer Learning ([Wikipedia page](https://en.wikipedia.org/wiki/Inductive_transfer))\n",

Can we add some detailed description of what transfer learning is? Where it is useful? etc

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:16 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "def download_flowers_dataset(dataset_root = os.path.join(datasets_path, 'Flowers')):\n",

We need to do a try catch block with 3 retries: Please refer to CNTK 104 tutorial. When we download we need to locally cache the file.

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:82 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "def download_flowers_dataset(dataset_root = os.path.join(datasets_path, 'Flowers')):\n",

Typically we explain each data set. What they are and how they are organized / formatted. How CNTK will read it in and pass it to the model.

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:82 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "    for uri, file in zip(flowers_uris, flowers_files):\n",

this logic is good. We will need to look into different local caches for testing: refer to CNTK 104

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:95 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "        # get image paths and 0-based image labels\n",

Need an explanation of 0-based image labels.

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:107 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "        write_to_file('1k_img_map.txt', dataset_root, image_paths[idx_train], image_labels[idx_train])\n",

What happens if the directory is not writable

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:119 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "from cntk.utils import log_number_of_parameters, ProgressPrinter\n",

Need this somewhere right in the beginning. Additionally, please take a look at CNTK 104 for the device selection logic and additional logic around the isFast flag.

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:265 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "    feature_node = find_by_name(base_model, feature_node_name)\n",

Can we have a brief writeup on how to find different node names in a model since this is the first time someone will be preloading a model and playing with the individual layers.

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:324 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "    # Clone the desired layers with fixed weights\n",

a description of why cloning is needed. 

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:327 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "        CloneMethod.freeze if freeze else CloneMethod.clone,\n",

Why other options for clone methods  are inapplicable would be a nice to have.

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:329 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "    }\n",

Can we create a generic reader and reuse that code. You should be able to find the code in [https://github.com/Microsoft/CNTK/blob/v2.0.beta11.0/Tutorials/CNTK_206_Basic_GAN.ipynb](https://github.com/Microsoft/CNTK/blob/v2.0.beta11.0/Tutorials/CNTK_206_Basic_GAN.ipynb) (cell number 10)

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:372 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "    # Get minibatches of images and perform model training\n",

I already have a pretrained model. Why do i need to train? How is this training different than my previous training? These are some of the question that comes to a readers mind. Can we please clarify

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:385 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "    # load and format image (resize, RGB -> BGR, CHW -> HWC)\n",

Need a section to describe these formats and why it is needed.  

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:421 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "    hwc_format = np.ascontiguousarray(np.rollaxis(bgr_image, 2))\n",

can we please have a bit more explanation on why this is needed!

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:429 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "# Evaluates an image set using the provided model\n",

retrained model may be?

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:440 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by sayanpa** [comment]
>     "# Train only if no model exists yet or if make_mode is set to False\n",

this needs to be clarified as separate text block preceding this section.

---
Refers to: Tutorials/CNTK_208_Transfer_Learning.ipynb:552 in 6181829. [](commit_id = 618182907383d3f3d3444fd9154bc05142578782, deletion_comment = False)

**Comment by noodlefrenzy** [comment]
Wow, @sayanpa, thanks for the detailed comments! Seems like a lot of "best practices" for notebooks are in 104, whereas I was cribbing much of this code from 207 and the TL example. I'll revise and re-push. However, I'd love to talk to someone on the team about a few questions I have - places where you've asked for explanatory text and I don't really understand the _why_ well enough to explain.

**Comment by noodlefrenzy** [comment]
@sayanpa Please take a look at my revisions. I think I've addressed most, if not all of your comments and would love to have you take another look. Thanks!

**Comment by sayanpa** [comment]
This notebook has been merged with the master. Thanks for your contribution.

**Pull request closed without merging**
