### PR TITLE
add CPPEvalExtendedClient

### PR DESCRIPTION
**Pull request by weixsong**
Using [Language Understanding Model](https://github.com/Microsoft/CNTK/blob/master/Examples/Text/ATIS/README.md) as example to show how to use extended eval interface and give the sequence input vectors to LU network.

Also using one input sentence "BOS i would like to find a flight from charlotte to las vegas that makes a stop in st. louis EOS" to show how to decode from LU model.

And, I am putting this example in Examples\Evaluation to avoid bring in regression for currently End2End test solution, we could move it to End2End test in future and also provide some demo data.

currently this program output will be:

```
Output dimension: 127
Output name: outputs
Input node name: featuresCW
Input feature dimension: 944
Input node name: featuresNW
Input feature dimension: 944
Input node name: featuresPW
Input feature dimension: 944
Slot tag for sentence "BOS i would like to find a flight from charlotte to las vegas that makes a stop in st. louis EOS" is as followings:
         i -- B-fromloc.airport_name
     would -- I-transport_type
      like -- I-transport_type
        to -- I-transport_type
      find -- I-transport_type
         a -- B-fromloc.airport_name
    flight -- I-transport_type
      from -- I-transport_type
 charlotte -- B-depart_date.day_name
        to -- I-transport_type
       las -- B-fromloc.airport_name
     vegas -- B-fromloc.airport_name
      that -- B-toloc.airport_name
     makes -- I-transport_type
         a -- B-toloc.airport_name
      stop -- I-transport_type
        in -- I-transport_type
       st. -- I-transport_type
     louis -- B-fromloc.airport_name
```

Tested both on Release_CPU & Debug_Cpu mode

### CODE REVIEW

**Comment by weixsong** [comment]
@zhouwangzw , I have rebased this Extended client example, and tested both on release_cpu & debug_cpu mode, please take a look.
Thanks very much.

**Comment by zhouwangzw** [comment]
Thanks, @weixsong. I will look into it.

**Comment by zhouwangzw** [comment]
@weixsong The result above sounds not matching the expected result. The index in buildVocab() should start with, instead of 1, as the first line of the ATIS.vocab file is "</s>", not the BOS. 
The following is the result after changing the idx from 1 to 0:

Slot tag for sentence "BOS i would like to find a flight from charlotte to las vegas that makes a stop in st. louis EOS" is as followings:
         i -- I-transport_type
     would -- I-transport_type
      like -- I-transport_type
        to -- I-transport_type
      find -- I-transport_type
         a -- I-transport_type
    flight -- I-transport_type
      from -- I-transport_type
 charlotte -- B-fromloc.airport_name
        to -- I-transport_type
       las -- B-toloc.airport_name
     vegas -- I-toloc.airport_name
      that -- I-transport_type
     makes -- I-transport_type
         a -- I-transport_type
      stop -- I-transport_type
        in -- I-transport_type
       st. -- B-stoploc.airport_name
     louis -- I-state_name

**Comment by zhouwangzw** [comment]
This pull request has been merged into master with the commit [7f06c9](https://github.com/Microsoft/CNTK/commit/7f06c917cf33d3e3311871035be4599b092e4016#diff-dda32e5515bd1699024e498d4afab20a)

**Comment by weixsong** [comment]
Hi @zhouwangzw , thanks for merging this PR.
I was busy and did not see your comment about idx 1 issue, thanks very much for fix this issue.
:)

**Pull request closed without merging**
