### PR TITLE
fix 1bitsgd default in configure help text

### PR DESCRIPTION
**Pull request by wilhelmtell**
`default_use_1bitsgd` is a variable, not a function.

### CODE REVIEW

**Comment by alexeyo26** [comment]
Attention MS Reviewer: Build 3549

**Comment by wilhelmtell** [comment]
?

**Comment by alexeyo26** [comment]
Matan, sorry - I forgot to post, that we're reviewing your pull request. That message of mine is a part of review process :)

**Comment by wilhelmtell** [comment]
Ah alright, thanks :)

**Comment by alexeyo26** [comment]
We will soon integrate it. Thank you for the contribution!

**Comment by alexeyo26** [comment]
Attention MS Reviewer: Build 3550

**Pull request merged**
