### PR TITLE
add end empty line and delete spaces

### PR DESCRIPTION
**Pull request by weixsong**
removed some spaces after code line end,
add new empty line at file end.

### CODE REVIEW

**Comment by zhouwangzw** [comment]
@weixsong Is this pull request still valid, or it has been merged as a part of 852? Thanks.

**Comment by weixsong** [comment]
hi zhou, it's still valid pull request. PR 852 is a different patch not include this change

**Comment by zhouwangzw** [comment]
Thank you @weixsong. We will now integrate it.

**Comment by zhouwangzw** [comment]
@weixsong  Thank you very much for your effort to make CNTK better. The pull request has been integrated into master. Please check and let me know if you have any questions.

**Comment by zhouwangzw** [comment]
@weixsong  I am closing this pull request. Please feel free to reopen if needed.

**Pull request closed without merging**
