### PR TITLE
python 3 compatibility fix

### PR DESCRIPTION
**Pull request by stonebig**

### CODE REVIEW

**Comment by crutchcorn** [comment]
Why not merge this with #27 @stonebig ?

**Comment by stonebig** [comment]
1' Workflow on Github (at least for me): 
- look code,
- see an obvious improvment (with no impact elsewhere than on the file),
- click "edit" on the browser,
- propose the change.

120' Workflow on Github (at least for me): 
- look code,
- see an obvious improvment (with no impact elsewhere than on the file),
- fork the project
- download the whole project on my pc,
- "edit" with notepad ++ the faulty file,
- repeat until the 9 files with issues have been corrected (postpone you GirlFriend rendrz-vous)
- check all looks a complete change,
- commit on a new branche of your tree,
- synch this branch up to your tree on github,
- propose the change via a pull request.

**Comment by chrisbasoglu** [comment]
Thank you

**Comment by stonebig** [comment]
you're welcome. I hope this project will soon be compatible with Python 3, and may I hope, with mingwpy

**Pull request merged**
