### PR TITLE
Tutorial CNTK 106: Part A - Time series prediction with LSTM (Basics) bug fix

### PR DESCRIPTION
**Pull request by playgithub**
1. one more input sample (line 208)
2. correct the mapping of inputs and lables (line 218)

### CODE REVIEW

**Comment by sayanpa** [comment]
Could you just check in the notebook. Tutorials/CNTK_106A_LSTM_Timeseries_with_Simulated_Data.ipynb 
No need to merge other changes to master.

**Comment by sayanpa** [comment]
can you please merge with the master and just submit 1 file with the ipynb. Would like to take this fix as soon as you are done. The other changes are more related to project settings and not specific to the tutorial.

**Comment by playgithub** [comment]
Hi, the first is relevant: https://github.com/Microsoft/CNTK/pull/1743/commits/eb63d5b451773c670752b7adda67fc974b37e4a7

I don't know why the other commits are shown here, I'll check it, please ignore them.

**Comment by sayanpa** [comment]
Looks like the test tolerance needs to be adjusted. The test is under `CNTK\Tests\EndToEndTests\CNTKv2Python\Tutorials`. Could you please update the test and add it to this commit. I can then do the pull. If you want you can create a new PR with just these two files - one being the notebook and the other being the test.

**Comment by sayanpa** [comment]
Merge completed. Pulled your change and added the test. Closing this pull. Thanks for your contribution.

**Pull request closed without merging**
