### PR TITLE
modify swig to generate more C# classes

### PR DESCRIPTION
**Pull request by larcai**
to enable the generation of more c# classes via swig.
this is an attempt to give the managed library more momentum
this change includes std_unordered_set.i to look and feel like System.Collections.Generic.ICollection

### CODE REVIEW

**Comment by zhouwangzw** [comment]
@larcai Thank you for your contribution to CNTK! The pull request adds more C# classes via swig. Would you please elaborate on scenarios why these classes are required? They seems not needed for evaluation (this is currently the main purpose of the C# API), but not sufficient to provide support for training?

**Comment by larcai** [comment]
the evaluation api is limited, the idea is to eventually have managed assembly API to be equivalent to the python.  to allow building models and access to trainer via c#

for example: I would like to build this sample [SequenceClassification](https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceClassification/SimpleExample/Python/SequenceClassification.py) in C#

maybe a separate library for this?

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by huoyaoyuan** [comment]
I'm willing to see C# api to be equivalent to python. 👍

**Comment by JimSEOW** [comment]
@larcai [ could you join us ](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)and update your status to make .NET the first class citizen for CNTK?

**Comment by huoyaoyuan** [comment]
@JimSEOW I'd like to do something for this, as I want to use it in .NET. Is there any work needed?

**Comment by JimSEOW** [comment]
@huoyaoyuan  Dear Huo Yao Yuan, First, we gather people to this [link ](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306544472)to start getting feedback on what best to do next.

We need people to start port python notebooks to .NET. See the link please thank you.

**Comment by JimSEOW** [comment]
@zhouwangzw do you have the latest version of managed dll that includes these extra C# classes? I would like to test what @larcai  have done to start setting up CNTK Model using C#

**Comment by zhouwangzw** [comment]
@JimSEOW The current C# dll does not include those C# classes yet. You need to build those classes by yourself. As Cha said, the team is currently planning post 2.0 work items. .NET support for training is one of tasks we are discussing. Please stay tuned. 
Thanks,

**Comment by JimSEOW** [comment]
@zhouwangzw 

We are now supporting XAMARIN to put .NET deep Learning to Xamarin Workbook. We have [examples from tensorflowSharp and the latest new comers from accord-NET](https://github.com/mattleibow/cognibooks), 

It will be Really sad that we STILL DO NOT have .NET CNTK workbook to promote .NET deep learning to students and education ecosystem in Universities.  

It will be really sad that the CNTK team HAS NOT Imagination to see the similarity between the potential impact of Xamarin Workbook and how Mathlab notebook has done to the education ecosystem.

**Comment by cha-zhang** [comment]
@larcai Thanks for the contribution! We have started working on C# API and you will see our progress in our Aug-Sep iteration. I'm closing this PR for now. Thanks!

**Pull request closed without merging**
