### PR TITLE
add example that show how to use extended eval interface

### PR DESCRIPTION
**Pull request by weixsong**
add example that show how to use extended eval interface to load a LSTM network, also show how to give input sequence vectors to LSTM.

### CODE REVIEW

**Comment by zhouwangzw** [comment]
@weixsong: Thank you for your effort. We will look into it.

**Comment by zhouwangzw** [comment]
@weixsong: I have sent you some comments on the code. I am glad to work together with you on these comments and then get your example integrated. 

Zhou

**Comment by weixsong** [comment]
Hi @zhouwangzw , where did you put your comments? I could not found the comments on https://github.com/Microsoft/CNTK/pull/770/files

**Comment by madingo87** [comment]
Is it the same when using the evalwrapper.dll (e.g. C#)?

**Comment by zhouwangzw** [comment]
@madingo87 Yes. You can use C# interface, e.g.  ModelEvaluationExtendedF() to call Eval extended interface.
Currently, you need to look into the example from @weixsong in his pull request. After he completes the change, it will be merged into master. 

Thanks,
Zhou

**Comment by zhouwangzw** [comment]
@weixsong  Thanks for your effort to create the example. As discussed per email, after you finish the comments, please let me know and we can work on integration into master.

**Comment by madingo87** [comment]
Ok thanks, I'll try to adapt it in my c# code!

**Comment by weixsong** [comment]
@zhouwangzw , I will finish the comments ASAP.

**Pull request closed without merging**
