### PR TITLE
Fixed the projects that were always considered out of date.

### PR DESCRIPTION
**Pull request by Ark-kun**
Solution: Fixed the header files in some projects.

### CODE REVIEW

**Comment by wolfma61** [comment]
please sign the cla

**Comment by Ark-kun** [comment]
I've already signed the CLA and you've already merged my PRs in the past. https://github.com/Microsoft/CNTK/pull/93
What has happened?

**Comment by Ark-kun** [comment]
@wolfma61 Signed the CLA again...

**Comment by mahilleb-msft** [comment]
Hi @Ark-kun, I believe we can close this here? This change has been integrated into master.

Thanks, Mark

**Comment by mahilleb-msft** [comment]
Closing, this was integrated as bf6a49d8cd0c71e9984069f53fd9433418b3b225.

**Pull request closed without merging**
