### PR TITLE
Add OpenMPI selection in configure and Makefile. 

### PR DESCRIPTION
**Pull request by jplu**
The configure and the Makefile have been modified in order to let the user set the proper location for the OpenMPI library.

### CODE REVIEW

**Comment by jplu** [comment]
This PR makes reference to the issue #269.

**Comment by mahilleb-msft** [comment]
Hi @jplu, thank you for your pull request!

For the Makefile changes, can't we instead let CXX point to the right mpic++ from the MPI installation?
I.e., use $(OPENMPI_PATH)/bin/mpic++ ? I think the INCLUDEPATH and LIBPATH shouldn't then be necessary...

**Comment by jplu** [comment]
Very good idea for the  mpic++ binary, I forgot that part.

I don't know if I properly set the mpic++, the corresponding INCLUDEPATH and LIBPATH will be used if another OpenMPI installation exists on the machine in ```/usr/lib``` folder, but worth to try. I gonna do some tests and will let you know here if it works as expected.

**Comment by jplu** [comment]
You had right, good catch :)

I modified only the location of the mpic++ binary and removing the changes for the INCLUDEPATH and LIBPATH.

**Comment by jplu** [comment]
Any news for this PR? :-)

**Comment by YanMinge** [comment]
@jplu ,You solved my compilation error, Thanks.

**Comment by jplu** [comment]
I can see that my PR has been taken into account by adding its changes into the current branch :) Thanks a lot!

I can close it.

**Comment by jplu** [comment]
New rebase to align my PR with the current branch.

**Comment by jplu** [comment]
New rebase to align my PR with the current branch.

**Comment by junjieqian** [comment]
@jplu, thank you for your contribution! The changes in master now.

**Pull request closed without merging**
