### PR TITLE
Fix Kaldi2Reader building.

### PR DESCRIPTION
**Pull request by yzhang87**
1. adding new virtual function. but this is just to fix compile issue, for multi utt support, need more work.
2. Someone remove a '}". Just add it back.

### CODE REVIEW

**Comment by amitaga** [comment]
Yu, can you please sign the CLA per the instructions at https://github.com/Microsoft/CNTK/wiki/Contributing-to-CNTK

**Comment by yzhang87** [comment]
Should I email the signed document to you? or there is an online version?

thanks

**Comment by alexeyo26** [comment]
Yu, sorry about this. The instructions were supposed to automatically appear inside the pool request – something went wrong this time.

Anyway, it’s simple. Go to https://cla.microsoft.com/ and follow the instructions. The whole process is online.

Sorry once again and thank you.
Alexey

**Comment by yzhang87** [comment]
done.

**Comment by alexeyo26** [comment]
Yu, thank you, we really appreciate it and sorry about this technical glitch.
Now we will proceed with the request.

Thank you,
Alexey.

**Comment by alexeyo26** [comment]
Attention MS Reviewer: Build 3039

**Comment by mahilleb-msft** [comment]
@yzhang87 - can you make your last two changes a separate PR? We are going to integrate the original PR fixing the build soon...
Thank you! Mark

**Comment by mahilleb-msft** [comment]
(Will start the integration of 367db5e76e5d11f78b8222baf90caa3fbc73bd35)

**Comment by yzhang87** [comment]
sure, sorry, I want to make a separate one but don't know how.

How can I revoke my second change?

thanks,
Yu

On Mon, Feb 29, 2016 at 5:42 AM, Mark Hillebrand <notifications@github.com>
wrote:

> @yzhang87 <https://github.com/yzhang87> - can you make your last two
> changes a separate PR? We are going to integrate the original PR fixing the
> build soon...
> Thank you! Mark
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/CNTK/pull/154#issuecomment-190148462>.
>



-- 
Yu Zhang
Computer Science and Artificial Intelligence Laboratory (CSAIL)
Massachusetts Institute of Technology

**Comment by mahilleb-msft** [comment]
@yzhang87 I'm trying to integrate just your initial change.
To "revoke" it from, you should do a new branch for your new changes (so, make sure you don't lose any of your additional changes). Then, changing back to the old branch, you can hard-reset it to revision 367db5e via "git reset --hard", and force-push your the branch again using "git push -f". This PR should then automatically update (unless the integration for which an attempt is in-progress previously closes this request).

THanks, Mark

**Comment by mahilleb-msft** [comment]
@yzhang87, I've integrated the first commit (367db5e76e5d11f78b8222baf90caa3fbc73bd35) on Monday. PR didn't updated here, probably because the PR wasn't merged in completely. Closing this here.

Many thanks!

**Comment by yzhang87** [comment]
ok, I will revoke the other two commits.

On Thu, Mar 3, 2016 at 3:25 PM, Mark Hillebrand <notifications@github.com>
wrote:

> @yzhang87 <https://github.com/yzhang87>, I've integrated the first commit
> (367db5e
> <https://github.com/Microsoft/CNTK/commit/367db5e76e5d11f78b8222baf90caa3fbc73bd35>)
> on Monday. PR didn't updated here, probably because the PR wasn't merged in
> completely. Closing this here.
>
> Many thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/CNTK/pull/154#issuecomment-191947878>.
>



-- 
Yu Zhang
Computer Science and Artificial Intelligence Laboratory (CSAIL)
Massachusetts Institute of Technology

**Pull request closed without merging**
