### PR TITLE
add example that show how to use extended eval interface

### PR DESCRIPTION
**Pull request by weixsong**
Using [Language Understanding Model](https://github.com/Microsoft/CNTK/blob/master/Examples/Text/ATIS/README.md) as example to show how to use extended eval interface and give the sequence input vectors to LU network.

Also using one input sentence <code>"BOS i would like to find a flight from charlotte to las vegas that makes a stop in st. louis EOS"</code> to show how to decode from LU model.

And, I am putting this example in <code>Examples\Evaluation</code> to avoid bring in regression for currently End2End test solution, we could move it to End2End test in future and also provide some demo data.

currently this program output will be:
```
Output dimension: 127
Output name: outputs
Input node name: featuresCW
Input feature dimension: 944
Input node name: featuresNW
Input feature dimension: 944
Input node name: featuresPW
Input feature dimension: 944
Output node name: outputs
Output feature dimension: 127
Slot tag for sentence "BOS i would like to find a flight from charlotte to las vegas that makes a stop in st. louis EOS" is as followings:
         i -- I-transport_type
     would -- B-fromloc.airport_name
      like -- I-transport_type
        to -- I-transport_type
      find -- I-transport_type
         a -- I-transport_type
    flight -- B-fromloc.airport_name
      from -- B-depart_time.time
 charlotte -- I-transport_type
        to -- B-fromloc.airport_name
       las -- I-transport_type
     vegas -- B-airline_code
      that -- I-transport_type
     makes -- B-toloc.airport_name
         a -- I-transport_type
      stop -- B-toloc.airport_name
        in -- I-transport_type
       st. -- I-transport_type
     louis -- I-transport_type
```

### CODE REVIEW

**Comment by weixsong** [comment]
@zhouwangzw , I have rebased the example, please take a look of the code and give me some comments.
Thanks very much.

**Comment by zhouwangzw** [comment]
@weixsong  Thank you VERY much for your effort. I will look into it ASAP.

**Comment by zhouwangzw** [comment]
@weixsong It seems that the CPPEvalExtendedClient.vcxproj is included neither in cntk.sln nor EvalExample.sln. If you do not mind, I can add the project into the solution file and fix some settings.

**Comment by weixsong** [comment]
@zhouwangzw , yes, it's not included in any solution intendedly. I am using VS2015, I am afraid to change the sln file too much by adding this project.
Please go ahead to add the project into solution.

**Comment by zhouwangzw** [comment]
@weixsong understood. I will integrate the project into both solutions.

**Comment by zhouwangzw** [comment]
@weixsong I am trying to integrate your pull request, but see an exception when running with the latest master. I have sent you in a separate email about it. Could you please take a look? Thank you very much!

**Comment by weixsong** [comment]
@zhouwangzw , OK, I will look into it.

**Comment by weixsong** [comment]
create a new PR [https://github.com/Microsoft/CNTK/pull/899](https://github.com/Microsoft/CNTK/pull/899)
closed this old one.

**Pull request closed without merging**
