### PR TITLE
Added missing quote in case OPENCV_PATH contains spaces.

### PR DESCRIPTION
**Pull request by rold2007**

### CODE REVIEW

**Comment by alexeyo26** [comment]
Thank you - we're processing the request. More soon

**Comment by alexeyo26** [comment]
Attention MS Reviewer: Build 2744

**Comment by mahilleb-msft** [comment]
Thank you, we will now integrate this.

**Comment by rold2007** [comment]
Note that my commit is probably only a partial fix to #85 but I only corrected what was affecting my compilation.

**Pull request merged**
