### PR TITLE
Adding useRandomDropout option into SGD block

### PR DESCRIPTION
**Pull request by jakrivan**
This is to add an optional randomization of dropout process.
Should address issue https://github.com/Microsoft/CNTK/issues/1178

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by chrisbasoglu** [comment]
Thank you for your contribution.  

This change (when enabled) unfortunately adds non determinism by using a time based random seed and will break checkpointing as well as reproducibility.

In the CNTK v2 APIs, we allow users to explicitly set the random seed for the dropout nodes which allows achieving the desired results without losing reproducibility and determinism. If the user wants this functionality in V1, a better way would be add a new randomSeedBase option in the config that will be added to the seed base used for RNG nodes and give users explicit control over varying the randomness across networks and runs if desired, without losing reproducibility and determinism.

**Comment by jakrivan** [comment]
Hi chrisbasoglu - thanks for your feedback.

The reproducibility and determinsm was the exact reason why 'useRandomDropout' was made optional and with default being false. That way you can remove this from your config and keep the deterministic behavior.

I agree that having the seed in config is even better though - I'll try to find some spare time to alter the code to this.

In any case - can you please point me to the code or documentation for the behavior you mentioned:

> In the CNTK v2 APIs, we allow users to explicitly set the random seed for the dropout nodes

This might be quite helpful to us.

Thanks
Jan

**Comment by chrisbasoglu** [comment]
Sorry we are adding this feature in right now.  Look for it in master in a few days.

Chris

**Pull request closed without merging**
