### PR TITLE
Revert "Revert "Add ReasoNet model as example""

### PR DESCRIPTION
**Pull request by xgk**
This reverts commit 570a7658870ba31dd41fd937041633a2f1345aee.

Revert "Revert "Add loss/pred for ReasoNet""

This reverts commit 77e5d159ce473fb2646c591ca06c40076a322810.

Revert "Revert "Add training method for ReasoNet""

This reverts commit d1bed651f098ebae55befa988d9457d38895129b.

Revert "Revert "Fix training issues with ReasoNet""

This reverts commit 510595348fde47e635cf44fc70558b5ad5618164.

### CODE REVIEW

**Comment by xgk** [comment]
@wzchen is added to the review. #Closed

**Comment by xgk** [comment]
@nikosk is added to the review. #Closed

**Comment by xgk** [comment]
@amitaga is added to the review. #Closed

**Comment by xgk** [comment]
@clemensm is added to the review. #Closed

**Comment by xgk** [comment]
@rohitka is added to the review. #Closed

**Comment by xgk** [comment]
@wdarling is added to the review. #Closed

**Comment by xgk** [comment]
@Yeshen is added to the review. #Closed

**Comment by sayanpa** [comment]
Closing this PR since the code base has drifted away significantly. Happy to take the changes in case you are interested in rebasing the branch against master. Please reissue the PR in that case.

**Pull request closed without merging**
