### PR TITLE
Add Markdown versions of documentation Word files

### PR DESCRIPTION
**Pull request by samjabrahams**
I went through and converted each .docx file in the Documentation/Documents folder into a Markdown file. Having documentation that is easily viewable and navigable on the web will be incredibly important if this open source effort is going to succeed. There will inevitably need to be changes and upgrades to these files, but I think this is a good first step.

I understand that there's a lot to look at, so taking a look at the rendered files will be the easiest way to make sure nothing looks screwy. Here are direct links to the files on my fork:

* [Configuration Files](https://github.com/samjabrahams/CNTK/blob/markdown-docs/Documentation/Documents/Configuration%20Files.md)
* [ExternalBuffer in Matrix class](https://github.com/samjabrahams/CNTK/blob/markdown-docs/Documentation/Documents/External%20Buffer%20Behavior.md)
* [Model Editing Language](https://github.com/samjabrahams/CNTK/blob/markdown-docs/Documentation/Documents/Model%20Editing%20Language.md)
* [Network Description Language](https://github.com/samjabrahams/CNTK/blob/markdown-docs/Documentation/Documents/Network%20Description%20Language.md)

_Note: while I may have made a few fixes, capitalization fixes, etc. while going through these files, I did not edit them for content. Fixing existing typos and grammatical errors was not the purpose of this PR._

### CODE REVIEW

**Comment by samjabrahams** [comment]
Fixed CR line endings and squashed the commit.

**Comment by chrisbasoglu** [comment]
Hi Sam.  Thank you for this.  Would it be possible for you update this change to delete the word docs too.  That way, we will only have to update one set of docs -- the new ones you have created.

**Comment by samjabrahams** [comment]
Done!

**Comment by chrisbasoglu** [comment]
Thank you.

**Pull request merged**
